### ISSUE TITLE
`z_stream` defined `intent(in)` in the interface functions

### ISSUE THREAD

**Issue by perazz** [interkosmos/fortran-zlib#1]
I've tried your zlib interface on my Mac M1 with gfortran-11 as an alternative to f95zlib. The code builds OK, but the test fails. 
The reason is that gfortran optimizes out some operations, because the `z_stream` is always defined as `intent(in)` in the interface functions to the C routines. That's in general not true, because zlib changes its contents, but the fortran compiler thinks it doesn't.

For example, in `zip_deflate_mem`, `have` always returns 0, because the stream structure is supposedly not changed by the call to deflate. 

```
            strm%avail_out = len(buffer)
            strm%next_out = c_loc(buffer)

            rc = deflate(strm, Z_FINISH)
            if (rc == Z_STREAM_ERROR) exit def_block
            have = len(buffer) - strm%avail_out ! returns 0
            dest = buffer(1:have)

```

I believe gfortran is doing this right, and the simple fix is to define the stream to be `intent(inout)` in all functions of the interface, e.g.:

```
        function deflate_end(strm) bind(c, name='deflateEnd')
            import :: c_int, z_stream
            implicit none
            type(z_stream), intent(inout) :: strm
            integer(kind=c_int)        :: deflate_end
        end function deflate_end
```

**Comment by interkosmos** [comment]
The bug also occurs if the library is compiled with optimisations (`-O3`). Thank you for reporting, has been fixed.
